/**
 * Kinship term dataset, distilled from the user's comparative workbook
 * ("kinship_term_systems_chart_expanded_2c.xlsx", sheets "2C expandable long"
 * + "Relation codes to 2C") with agreed corrections:
 *   - romanisation normalised per language to one named scheme;
 *   - Tamil/Telugu cross-cousin lexemes filled in (flagged with an N.B.);
 *   - N.B.s added where a term is not universal (Japanese 伯/叔, Vietnamese
 *     bác, Mandarin 姨, the four structural-type rows);
 *   - core relations (parent…nephew) added as tool extensions so the whole
 *     genealogy tree is navigable. These carry source: "tool-added".
 *
 * Entry shape (all fields optional except `k`):
 *   k    "term" | "recipe" | "class"   how to realise it
 *   t    native-script term            (term/class)
 *   r    romanisation                  (term)
 *   g    short English gloss
 *   e    etymological / graphic note
 *   u    usage / reliability note
 *   nb   an N.B. the user might want (term not universal, etc.)
 *   rec  recipe spec for the composer  (recipe; see kinship-compose.js)
 *   src  source key into SOURCES
 */

export const SOURCES = {
  kinbank: "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0283218",
  qian: "https://ucrel.lancs.ac.uk/publications/CL2007/paper/63_Paper.pdf",
  sidnell: "https://rai.onlinelibrary.wiley.com/doi/10.1111/1467-9655.12053",
  korean: "https://www.ijcar.net/assets/pdf/Vol6-No1-January2019/06.pdf",
  chon: "https://languagelog.ldc.upenn.edu/nll/?p=27637",
  surya: "https://journals.rudn.ru/linguistics/article/view/26001",
  dravidian: "https://journals.openedition.org/lhomme/21745?lang=en",
  murrinh: "https://pure.mpg.de/rest/items/item_1836485_7/component/file_2629912/content",
  tooladded: null,
};

export const LANGUAGES = [
  { id: "zh", name: "Mandarin Chinese", family: "Sino-Tibetan", roman: "Pinyin", wikt: "Chinese", structural: false },
  { id: "yue", name: "Cantonese", family: "Sino-Tibetan", roman: "Jyutping", wikt: "Chinese", structural: false },
  { id: "ja", name: "Japanese", family: "Japonic", roman: "Hepburn", wikt: "Japanese", structural: false },
  { id: "ko", name: "Korean", family: "Koreanic", roman: "Revised Romanization", wikt: "Korean", structural: false },
  { id: "vi", name: "Vietnamese", family: "Austroasiatic", roman: "Quốc ngữ", wikt: "Vietnamese", structural: false },
  { id: "hi", name: "Hindi", family: "Indo-European", roman: "IAST", wikt: "Hindi", structural: false },
  { id: "bn", name: "Bengali", family: "Indo-European", roman: "IAST", wikt: "Bengali", structural: false },
  { id: "ta", name: "Tamil", family: "Dravidian", roman: "ISO 15919", wikt: "Tamil", structural: false },
  { id: "te", name: "Telugu", family: "Dravidian", roman: "ISO 15919", wikt: "Telugu", structural: false },
  { id: "ar", name: "Arabic", family: "Semitic", roman: "ALA-LC", wikt: "Arabic", structural: false },
  { id: "tr", name: "Turkish", family: "Turkic", roman: "—", wikt: "Turkish", structural: false },
  { id: "iroq", name: "Iroquoian-type", family: "structural type", roman: "", wikt: null, structural: true },
  { id: "crow", name: "Crow-type", family: "structural type", roman: "", wikt: null, structural: true },
  { id: "omaha", name: "Omaha-type", family: "structural type", roman: "", wikt: null, structural: true },
  { id: "mur", name: "Murrinhpatha / Australian", family: "non-Pama-Nyungan", roman: "", wikt: null, structural: true },
];

/** Canonical relations the resolver can produce. */
export const RELATIONS = {
  SELF: { label: "self (ego)", core: true },
  FATHER: { label: "father", core: true },
  MOTHER: { label: "mother", core: true },
  GRANDFATHER_PAT: { label: "paternal grandfather", core: true },
  GRANDMOTHER_PAT: { label: "paternal grandmother", core: true },
  GRANDFATHER_MAT: { label: "maternal grandfather", core: true },
  GRANDMOTHER_MAT: { label: "maternal grandmother", core: true },
  BROTHER: { label: "brother", core: true },
  SISTER: { label: "sister", core: true },
  SON: { label: "son", core: true },
  DAUGHTER: { label: "daughter", core: true },
  GRANDCHILD: { label: "grandchild", core: true },
  GREAT_GRANDPARENT: { label: "great-grandparent", core: true },
  GREAT_GRANDCHILD: { label: "great-grandchild", core: true },
  NIBLING: { label: "nephew / niece", core: true },
  PARENT_SIBLING_PAT: { label: "paternal aunt/uncle", src: "qian" },
  PARENT_SIBLING_MAT: { label: "maternal aunt/uncle", src: "qian" },
  "1C_PAT_PARALLEL": { label: "first cousin, paternal parallel" },
  "1C_PAT_CROSS": { label: "first cousin, paternal cross" },
  "1C_MAT_CROSS": { label: "first cousin, maternal cross" },
  "1C_MAT_PARALLEL": { label: "first cousin, maternal parallel" },
  "1C1R_UP": { label: "first cousin once removed (ascending)" },
  "1C1R_DOWN": { label: "first cousin once removed (descending)" },
  "2C_PAT_AGNATIC": { label: "second cousin, paternal agnatic" },
  "2C_NONAGNATIC": { label: "second cousin, non-agnatic" },
  "2C1R_TEMPLATE": { label: "second cousin once removed" },
  DISTANT_TEMPLATE: { label: "distant cousin" },
  ANCESTOR_TEMPLATE: { label: "remote ancestor" },
  DESCENDANT_TEMPLATE: { label: "remote descendant" },
  GRANDPARENT_SIBLING_TEMPLATE: { label: "grand-aunt / grand-uncle" },
};

const T = (k, o = {}) => ({ k, ...o });

/**
 * entries[relationId][langId] -> entry. A missing cell falls through to a
 * generated "no charted term" placeholder in the UI.
 */
export const ENTRIES = {
  /* ---- core lineal / sibling / child (tool-added) ---- */
  FATHER: {
    zh: T("term", { t: "父亲 / 爸爸", r: "fùqīn / bàba", g: "father" }),
    yue: T("term", { t: "阿爸 / 爸爸", r: "aa3-baa1 / baa4-baa1", g: "father" }),
    ja: T("term", { t: "父 / お父さん", r: "chichi / otōsan", g: "father" }),
    ko: T("term", { t: "아버지", r: "abeoji", g: "father" }),
    vi: T("term", { t: "cha / bố", r: "cha / bố", g: "father" }),
    hi: T("term", { t: "पिता", r: "pitā", g: "father" }),
    bn: T("term", { t: "বাবা", r: "bābā", g: "father" }),
    ta: T("term", { t: "அப்பா", r: "appā", g: "father" }),
    te: T("term", { t: "నాన్న", r: "nānna", g: "father" }),
    ar: T("term", { t: "أب", r: "ʾab", g: "father" }),
    tr: T("term", { t: "baba", r: "baba", g: "father" }),
    iroq: T("class", { t: "FATHER (often merges with father's brother)" }),
    crow: T("class", { t: "father; FB-class may merge" }),
    omaha: T("class", { t: "father; FB-class may merge" }),
    mur: T("class", { t: "language-specific term; check community source" }),
  },
  MOTHER: {
    zh: T("term", { t: "母亲 / 妈妈", r: "mǔqīn / māma", g: "mother" }),
    yue: T("term", { t: "阿媽 / 媽媽", r: "aa3-maa1 / maa4-maa1", g: "mother" }),
    ja: T("term", { t: "母 / お母さん", r: "haha / okāsan", g: "mother" }),
    ko: T("term", { t: "어머니", r: "eomeoni", g: "mother" }),
    vi: T("term", { t: "mẹ", r: "mẹ", g: "mother" }),
    hi: T("term", { t: "माँ", r: "mā̃", g: "mother" }),
    bn: T("term", { t: "মা", r: "mā", g: "mother" }),
    ta: T("term", { t: "அம்மா", r: "ammā", g: "mother" }),
    te: T("term", { t: "అమ్మ", r: "amma", g: "mother" }),
    ar: T("term", { t: "أم", r: "ʾumm", g: "mother" }),
    tr: T("term", { t: "anne", r: "anne", g: "mother" }),
    iroq: T("class", { t: "MOTHER (often merges with mother's sister)" }),
    crow: T("class", { t: "mother; MZ-class may merge" }),
    omaha: T("class", { t: "mother; MZ-class may merge" }),
    mur: T("class", { t: "language-specific term; check community source" }),
  },
  BROTHER: {
    zh: T("term", { t: "哥哥 / 弟弟", r: "gēge / dìdi", g: "elder / younger brother", nb: "Mandarin lexicalises sibling age: 哥 elder, 弟 younger." }),
    yue: T("term", { t: "哥哥 / 細佬", r: "go4-go1 / sai3-lou2", g: "elder / younger brother" }),
    ja: T("term", { t: "兄 / 弟", r: "ani / otōto", g: "elder / younger brother" }),
    ko: T("term", { t: "형 / 오빠 / 남동생", r: "hyeong / oppa / namdongsaeng", g: "elder bro (of ♂ / ♀) / younger bro", nb: "Elder-brother term depends on the speaker's gender: 형 for a male speaker, 오빠 for a female speaker." }),
    vi: T("term", { t: "anh / em trai", r: "anh / em trai", g: "elder / younger brother" }),
    hi: T("term", { t: "भाई", r: "bhāī", g: "brother" }),
    bn: T("term", { t: "দাদা / ভাই", r: "dādā / bhāi", g: "elder / younger brother" }),
    ta: T("term", { t: "அண்ணன் / தம்பி", r: "aṇṇaṉ / tampi", g: "elder / younger brother" }),
    te: T("term", { t: "అన్న / తమ్ముడు", r: "anna / tammuḍu", g: "elder / younger brother" }),
    ar: T("term", { t: "أخ", r: "ʾakh", g: "brother" }),
    tr: T("term", { t: "ağabey / kardeş", r: "ağabey / kardeş", g: "elder brother / sibling" }),
    iroq: T("class", { t: "brother (parallel cousins may merge here)" }),
    crow: T("class", { t: "brother" }),
    omaha: T("class", { t: "brother" }),
    mur: T("class", { t: "language-specific term; check community source" }),
  },
  SISTER: {
    zh: T("term", { t: "姐姐 / 妹妹", r: "jiějie / mèimei", g: "elder / younger sister" }),
    yue: T("term", { t: "家姐 / 細妹", r: "gaa1-ze1 / sai3-mui6", g: "elder / younger sister" }),
    ja: T("term", { t: "姉 / 妹", r: "ane / imōto", g: "elder / younger sister" }),
    ko: T("term", { t: "누나 / 언니 / 여동생", r: "nuna / eonni / yeodongsaeng", g: "elder sis (of ♂ / ♀) / younger sis", nb: "Elder-sister term depends on the speaker's gender: 누나 for a male speaker, 언니 for a female speaker." }),
    vi: T("term", { t: "chị / em gái", r: "chị / em gái", g: "elder / younger sister" }),
    hi: T("term", { t: "बहन", r: "bahan", g: "sister" }),
    bn: T("term", { t: "দিদি / বোন", r: "didi / bon", g: "elder / younger sister" }),
    ta: T("term", { t: "அக்கா / தங்கை", r: "akkā / taṅkai", g: "elder / younger sister" }),
    te: T("term", { t: "అక్క / చెల్లి", r: "akka / celli", g: "elder / younger sister" }),
    ar: T("term", { t: "أخت", r: "ʾukht", g: "sister" }),
    tr: T("term", { t: "abla / kardeş", r: "abla / kardeş", g: "elder sister / sibling" }),
    iroq: T("class", { t: "sister (parallel cousins may merge here)" }),
    crow: T("class", { t: "sister" }),
    omaha: T("class", { t: "sister" }),
    mur: T("class", { t: "language-specific term; check community source" }),
  },
  SON: {
    zh: T("term", { t: "儿子", r: "érzi", g: "son" }),
    yue: T("term", { t: "仔", r: "zai2", g: "son" }),
    ja: T("term", { t: "息子", r: "musuko", g: "son" }),
    ko: T("term", { t: "아들", r: "adeul", g: "son" }),
    vi: T("term", { t: "con trai", r: "con trai", g: "son" }),
    hi: T("term", { t: "बेटा", r: "beṭā", g: "son" }),
    bn: T("term", { t: "ছেলে", r: "chele", g: "son" }),
    ta: T("term", { t: "மகன்", r: "makaṉ", g: "son" }),
    te: T("term", { t: "కొడుకు", r: "koḍuku", g: "son" }),
    ar: T("term", { t: "ابن", r: "ibn", g: "son" }),
    tr: T("term", { t: "oğul", r: "oğul", g: "son" }),
    iroq: T("class", { t: "son (own / parallel niblings may merge)" }),
    crow: T("class", { t: "son" }),
    omaha: T("class", { t: "son" }),
    mur: T("class", { t: "language-specific term; check community source" }),
  },
  DAUGHTER: {
    zh: T("term", { t: "女儿", r: "nǚ'ér", g: "daughter" }),
    yue: T("term", { t: "女", r: "neoi2", g: "daughter" }),
    ja: T("term", { t: "娘", r: "musume", g: "daughter" }),
    ko: T("term", { t: "딸", r: "ttal", g: "daughter" }),
    vi: T("term", { t: "con gái", r: "con gái", g: "daughter" }),
    hi: T("term", { t: "बेटी", r: "beṭī", g: "daughter" }),
    bn: T("term", { t: "মেয়ে", r: "meye", g: "daughter" }),
    ta: T("term", { t: "மகள்", r: "makaḷ", g: "daughter" }),
    te: T("term", { t: "కూతురు", r: "kūturu", g: "daughter" }),
    ar: T("term", { t: "بنت", r: "bint", g: "daughter" }),
    tr: T("term", { t: "kız", r: "kız", g: "daughter" }),
    iroq: T("class", { t: "daughter" }),
    crow: T("class", { t: "daughter" }),
    omaha: T("class", { t: "daughter" }),
    mur: T("class", { t: "language-specific term; check community source" }),
  },
  GRANDFATHER_PAT: {
    zh: T("term", { t: "祖父 / 爷爷", r: "zǔfù / yéye", g: "father's father" }),
    yue: T("term", { t: "阿爺", r: "aa3-je4", g: "father's father" }),
    ja: T("term", { t: "祖父", r: "sofu", g: "grandfather" }),
    ko: T("term", { t: "할아버지", r: "harabeoji", g: "grandfather" }),
    vi: T("term", { t: "ông nội", r: "ông nội", g: "paternal grandfather" }),
    hi: T("term", { t: "दादा", r: "dādā", g: "paternal grandfather" }),
    bn: T("term", { t: "দাদু / ঠাকুরদা", r: "dādu / ṭhākurdā", g: "paternal grandfather" }),
    ta: T("term", { t: "தாத்தா", r: "tāttā", g: "grandfather" }),
    te: T("term", { t: "తాత", r: "tāta", g: "grandfather" }),
    ar: T("term", { t: "جد", r: "jadd", g: "grandfather" }),
    tr: T("term", { t: "dede", r: "dede", g: "grandfather" }),
    iroq: T("class", { t: "grandfather" }), crow: T("class", { t: "grandfather" }),
    omaha: T("class", { t: "grandfather" }), mur: T("class", { t: "community-specific term" }),
  },
  GRANDMOTHER_PAT: {
    zh: T("term", { t: "祖母 / 奶奶", r: "zǔmǔ / nǎinai", g: "father's mother" }),
    yue: T("term", { t: "阿嫲", r: "aa3-maa4", g: "father's mother" }),
    ja: T("term", { t: "祖母", r: "sobo", g: "grandmother" }),
    ko: T("term", { t: "할머니", r: "halmeoni", g: "grandmother" }),
    vi: T("term", { t: "bà nội", r: "bà nội", g: "paternal grandmother" }),
    hi: T("term", { t: "दादी", r: "dādī", g: "paternal grandmother" }),
    bn: T("term", { t: "ঠাকুমা", r: "ṭhākumā", g: "paternal grandmother" }),
    ta: T("term", { t: "பாட்டி", r: "pāṭṭi", g: "grandmother" }),
    te: T("term", { t: "నాయనమ్మ", r: "nāyanamma", g: "paternal grandmother" }),
    ar: T("term", { t: "جدة", r: "jadda", g: "grandmother" }),
    tr: T("term", { t: "babaanne", r: "babaanne", g: "paternal grandmother" }),
    iroq: T("class", { t: "grandmother" }), crow: T("class", { t: "grandmother" }),
    omaha: T("class", { t: "grandmother" }), mur: T("class", { t: "community-specific term" }),
  },
  GRANDFATHER_MAT: {
    zh: T("term", { t: "外祖父 / 外公", r: "wàizǔfù / wàigōng", g: "mother's father", e: "外 wài 'outside' marks the maternal side." }),
    yue: T("term", { t: "阿公 / 公公", r: "aa3-gung1 / gung4-gung1", g: "mother's father" }),
    ja: T("term", { t: "祖父", r: "sofu", g: "grandfather", nb: "Japanese does not lexicalise grandparent side; 母方の is added if needed." }),
    ko: T("term", { t: "외할아버지", r: "oe-harabeoji", g: "maternal grandfather", e: "외 oe marks the maternal/outside line." }),
    vi: T("term", { t: "ông ngoại", r: "ông ngoại", g: "maternal grandfather" }),
    hi: T("term", { t: "नाना", r: "nānā", g: "maternal grandfather" }),
    bn: T("term", { t: "দাদু / নানা", r: "dādu / nānā", g: "maternal grandfather" }),
    ta: T("term", { t: "தாத்தா", r: "tāttā", g: "grandfather" }),
    te: T("term", { t: "తాత", r: "tāta", g: "grandfather" }),
    ar: T("term", { t: "جد", r: "jadd", g: "grandfather" }),
    tr: T("term", { t: "dede", r: "dede", g: "grandfather" }),
    iroq: T("class", { t: "grandfather" }), crow: T("class", { t: "grandfather" }),
    omaha: T("class", { t: "grandfather" }), mur: T("class", { t: "community-specific term" }),
  },
  GRANDMOTHER_MAT: {
    zh: T("term", { t: "外祖母 / 外婆", r: "wàizǔmǔ / wàipó", g: "mother's mother", e: "外 wài marks the maternal side." }),
    yue: T("term", { t: "阿婆 / 婆婆", r: "aa3-po4 / po4-po2", g: "mother's mother" }),
    ja: T("term", { t: "祖母", r: "sobo", g: "grandmother" }),
    ko: T("term", { t: "외할머니", r: "oe-halmeoni", g: "maternal grandmother" }),
    vi: T("term", { t: "bà ngoại", r: "bà ngoại", g: "maternal grandmother" }),
    hi: T("term", { t: "नानी", r: "nānī", g: "maternal grandmother" }),
    bn: T("term", { t: "দিদিমা / নানি", r: "didimā / nāni", g: "maternal grandmother" }),
    ta: T("term", { t: "பாட்டி", r: "pāṭṭi", g: "grandmother" }),
    te: T("term", { t: "అమ్మమ్మ", r: "ammamma", g: "maternal grandmother" }),
    ar: T("term", { t: "جدة", r: "jadda", g: "grandmother" }),
    tr: T("term", { t: "anneanne", r: "anneanne", g: "maternal grandmother" }),
    iroq: T("class", { t: "grandmother" }), crow: T("class", { t: "grandmother" }),
    omaha: T("class", { t: "grandmother" }), mur: T("class", { t: "community-specific term" }),
  },
  GRANDCHILD: {
    zh: T("term", { t: "孙 / 孙女 / 外孙(女)", r: "sūn / sūnnǚ / wàisūn(nǚ)", g: "son's vs daughter's child", e: "外 wài marks a daughter's child (outside the agnatic line)." }),
    yue: T("term", { t: "孫 / 外孫", r: "syun1 / ngoi6-syun1", g: "grandchild" }),
    ja: T("term", { t: "孫", r: "mago", g: "grandchild" }),
    ko: T("term", { t: "손자 / 손녀", r: "sonja / sonnyeo", g: "grandson / granddaughter" }),
    vi: T("term", { t: "cháu", r: "cháu", g: "grandchild / junior kin" }),
    hi: T("term", { t: "पोता/पोती · नाती/नातिन", r: "potā/potī · nātī/nātin", g: "son's vs daughter's child" }),
    bn: T("term", { t: "নাতি / নাতনি", r: "nāti / nātni", g: "grandson / granddaughter" }),
    ta: T("term", { t: "பேரன் / பேத்தி", r: "pēraṉ / pētti", g: "grandson / granddaughter" }),
    te: T("term", { t: "మనవడు / మనవరాలు", r: "manavaḍu / manavarālu", g: "grandson / granddaughter" }),
    ar: T("term", { t: "حفيد / حفيدة", r: "ḥafīd / ḥafīda", g: "grandson / granddaughter" }),
    tr: T("term", { t: "torun", r: "torun", g: "grandchild" }),
    iroq: T("class", { t: "grandchild" }), crow: T("class", { t: "grandchild (may skew)" }),
    omaha: T("class", { t: "grandchild (may skew)" }), mur: T("class", { t: "community-specific term" }),
  },
  NIBLING: {
    zh: T("term", { t: "侄(女) / 外甥(女)", r: "zhí(nǚ) / wàishēng(nǚ)", g: "brother's vs sister's child", e: "侄 brother's child (agnatic); 外甥 sister's child." }),
    yue: T("term", { t: "侄 / 外甥", r: "zat6 / ngoi6-saang1", g: "brother's vs sister's child" }),
    ja: T("term", { t: "甥 / 姪", r: "oi / mei", g: "nephew / niece" }),
    ko: T("term", { t: "조카", r: "joka", g: "nephew / niece" }),
    vi: T("term", { t: "cháu", r: "cháu", g: "nephew / niece / junior kin" }),
    hi: T("term", { t: "भतीजा/भतीजी · भांजा/भांजी", r: "bhatījā/bhatījī · bhāñjā/bhāñjī", g: "brother's vs sister's child" }),
    bn: T("term", { t: "ভাইপো/ভাইঝি · ভাগ্নে/ভাগ্নি", r: "bhāipo/bhāijhi · bhāgne/bhāgni", g: "brother's vs sister's child" }),
    ta: T("term", { t: "மருமகன் / மருமகள்", r: "marumakaṉ / marumakaḷ", g: "nephew / niece (also son/daughter-in-law)", nb: "In Dravidian alliance terms the same word covers a cross-nephew and a child-in-law — the marriageable category." }),
    te: T("term", { t: "మేనల్లుడు / మేనకోడలు", r: "mēnalluḍu / mēnakōḍalu", g: "nephew / niece" }),
    ar: T("term", { t: "ابن الأخ / ابن الأخت", r: "ibn al-ʾakh / ibn al-ʾukht", g: "brother's vs sister's son" }),
    tr: T("term", { t: "yeğen", r: "yeğen", g: "nephew / niece" }),
    iroq: T("class", { t: "parallel nibling may merge with own child" }),
    crow: T("class", { t: "skewed by Crow logic" }),
    omaha: T("class", { t: "skewed by Omaha logic" }),
    mur: T("class", { t: "community-specific term" }),
  },

  SELF: {
    zh: T("term", { t: "我", r: "wǒ", g: "I / self" }),
    yue: T("term", { t: "我", r: "ngo5", g: "I / self" }),
    ja: T("term", { t: "自分", r: "jibun", g: "self" }),
    ko: T("term", { t: "나", r: "na", g: "I / self" }),
    vi: T("term", { t: "tôi", r: "tôi", g: "I / self" }),
    hi: T("term", { t: "मैं", r: "maĩ", g: "I" }),
    bn: T("term", { t: "আমি", r: "āmi", g: "I" }),
    ta: T("term", { t: "நான்", r: "nāṉ", g: "I" }),
    te: T("term", { t: "నేను", r: "nēnu", g: "I" }),
    ar: T("term", { t: "أنا", r: "ʾanā", g: "I" }),
    tr: T("term", { t: "ben", r: "ben", g: "I" }),
    iroq: T("class", { t: "ego — the reference point" }),
    crow: T("class", { t: "ego" }), omaha: T("class", { t: "ego" }), mur: T("class", { t: "ego" }),
  },
  GREAT_GRANDPARENT: {
    zh: T("term", { t: "曾祖父 / 曾祖母", r: "zēngzǔfù / zēngzǔmǔ", g: "great-grandparent", e: "曾 zēng marks the +3 generation; 外 prefixes the maternal line." }),
    yue: T("term", { t: "太爺 / 太嫲", r: "taai3-je4 / taai3-maa4", g: "great-grandparent" }),
    ja: T("term", { t: "曽祖父 / 曽祖母", r: "sōsofu / sōsobo", g: "great-grandfather / -mother" }),
    ko: T("term", { t: "증조부 / 증조모", r: "jeungjobu / jeungjomo", g: "great-grandparent" }),
    vi: T("term", { t: "cụ ông / cụ bà", r: "cụ ông / cụ bà", g: "great-grandparent" }),
    hi: T("term", { t: "परदादा / परदादी", r: "pardādā / pardādī", g: "great-grandparent", e: "पर par- marks one further remove." }),
    bn: T("term", { t: "বড় দাদু / বড় দিদা", r: "baṛo dādu / baṛo didā", g: "great-grandparent" }),
    ta: T("term", { t: "கொள்ளுத் தாத்தா / பாட்டி", r: "koḷḷut tāttā / pāṭṭi", g: "great-grandparent" }),
    te: T("term", { t: "ముత్తాత / ముత్తవ్వ", r: "muttāta / muttavva", g: "great-grandparent" }),
    ar: T("term", { t: "جد الجد", r: "jadd al-jadd", g: "great-grandparent (lit. grandfather's father)" }),
    tr: T("term", { t: "büyük dede / büyük nine", r: "büyük dede / büyük nine", g: "great-grandparent" }),
    iroq: T("class", { t: "+3 ascending; often merged with grandparent" }),
    crow: T("class", { t: "+3 ascending; may skew" }), omaha: T("class", { t: "+3 ascending; may skew" }),
    mur: T("class", { t: "community-specific term" }),
  },
  GREAT_GRANDCHILD: {
    zh: T("term", { t: "曾孙 / 曾孙女", r: "zēngsūn / zēngsūnnǚ", g: "great-grandchild", e: "曾 zēng marks the −3 generation; 外 a daughter's line." }),
    yue: T("term", { t: "曾孫", r: "cang1-syun1", g: "great-grandchild" }),
    ja: T("term", { t: "曽孫", r: "sōson / himago", g: "great-grandchild" }),
    ko: T("term", { t: "증손자 / 증손녀", r: "jeungsonja / jeungsonnyeo", g: "great-grandchild" }),
    vi: T("term", { t: "chắt", r: "chắt", g: "great-grandchild" }),
    hi: T("term", { t: "परपोता / परपोती", r: "parpotā / parpotī", g: "great-grandchild" }),
    bn: T("term", { t: "বড় নাতি / নাতনি", r: "baṛo nāti / nātni", g: "great-grandchild" }),
    ta: T("term", { t: "கொள்ளுப் பேரன் / பேத்தி", r: "koḷḷup pēraṉ / pētti", g: "great-grandchild" }),
    te: T("term", { t: "మునిమనవడు / మునిమనవరాలు", r: "munimanavaḍu / munimanavarālu", g: "great-grandchild" }),
    ar: T("term", { t: "ابن الحفيد", r: "ibn al-ḥafīd", g: "great-grandchild (lit. grandchild's child)" }),
    tr: T("term", { t: "torun çocuğu", r: "torun çocuğu", g: "great-grandchild" }),
    iroq: T("class", { t: "−3 descending" }),
    crow: T("class", { t: "−3 descending; may skew" }), omaha: T("class", { t: "−3 descending; may skew" }),
    mur: T("class", { t: "community-specific term" }),
  },
  GRANDPARENT_SIBLING_TEMPLATE: {
    zh: T("term", { t: "伯祖 / 叔祖 / 姑婆…", r: "bózǔ / shūzǔ / gūpó", g: "grandparent's sibling (grand-uncle / grand-aunt)" }),
    yue: T("term", { t: "伯公 / 叔公 / 姑婆", r: "baak3-gung1 / suk1-gung1 / gu1-po4", g: "grand-uncle / grand-aunt" }),
    ja: T("term", { t: "大伯父 / 大叔母", r: "ō-oji / ō-oba", g: "grand-uncle / grand-aunt" }),
    ko: T("term", { t: "종조부 / 대고모", r: "jongjobu / daegomo", g: "grandparent's sibling (5-chon ascending)" }),
    vi: T("term", { t: "ông chú / bà cô (họ)", r: "ông chú / bà cô họ", g: "grand-uncle / grand-aunt" }),
    hi: T("term", { t: "दादा/नाना के भाई-बहन", r: "dādā/nānā ke bhāī-bahan", g: "grandparent's sibling" }),
    bn: T("term", { t: "দাদু/দিদার ভাই-বোন", r: "dādu/didār bhāi-bon", g: "grandparent's sibling" }),
    ta: T("term", { t: "பாட்டனின் உடன்பிறந்தோர்", r: "pāṭṭaṉiṉ uṭaṉpiṟantōr", g: "grandparent's sibling" }),
    te: T("term", { t: "తాత తోబుట్టువు", r: "tāta tōbuṭṭuvu", g: "grandparent's sibling" }),
    ar: T("term", { t: "عم / خال الأب", r: "ʿamm / khāl al-ʾab", g: "grandparent's sibling (descriptive)" }),
    tr: T("term", { t: "büyük amca / büyük hala", r: "büyük amca / büyük hala", g: "grand-uncle / grand-aunt" }),
    iroq: T("class", { t: "classed with grandparent in many systems" }),
    crow: T("class", { t: "skewed / classificatory" }), omaha: T("class", { t: "skewed / classificatory" }),
    mur: T("class", { t: "community-specific term" }),
  },
  ANCESTOR_TEMPLATE: {
    zh: T("term", { t: "高祖 / 远祖", r: "gāozǔ / yuǎnzǔ", g: "remote ancestor (高 marks +4)" }),
    yue: T("term", { t: "高祖 / 遠祖", r: "gou1-zou2 / jyun5-zou2", g: "remote ancestor" }),
    ja: T("term", { t: "高祖父母 / 先祖", r: "kōsofubo / senzo", g: "remote ancestor" }),
    ko: T("term", { t: "고조부모 / 선조", r: "gojobumo / seonjo", g: "remote ancestor" }),
    vi: T("term", { t: "tổ tiên / cụ tổ", r: "tổ tiên", g: "ancestor" }),
    hi: T("term", { t: "पूर्वज", r: "pūrvaj", g: "ancestor" }),
    bn: T("term", { t: "পূর্বপুরুষ", r: "pūrbapuruṣ", g: "ancestor" }),
    ta: T("term", { t: "மூதாதையர்", r: "mūtātaiyar", g: "ancestor" }),
    te: T("term", { t: "పూర్వీకుడు", r: "pūrvīkuḍu", g: "ancestor" }),
    ar: T("term", { t: "سلف / جد أعلى", r: "salaf / jadd ʾaʿlā", g: "forebear" }),
    tr: T("term", { t: "ata / cet", r: "ata / cet", g: "ancestor" }),
    iroq: T("class", { t: "remote ascending kin" }),
    crow: T("class", { t: "remote ascending" }), omaha: T("class", { t: "remote ascending" }),
    mur: T("class", { t: "community-specific term" }),
  },
  DESCENDANT_TEMPLATE: {
    zh: T("term", { t: "玄孙 / 远裔", r: "xuánsūn / yuǎnyì", g: "remote descendant (玄 marks −4)" }),
    yue: T("term", { t: "玄孫 / 後代", r: "jyun4-syun1 / hau6-doi6", g: "remote descendant" }),
    ja: T("term", { t: "玄孫 / 子孫", r: "yashago / shison", g: "remote descendant" }),
    ko: T("term", { t: "현손 / 후손", r: "hyeonson / huson", g: "remote descendant" }),
    vi: T("term", { t: "con cháu / hậu duệ", r: "hậu duệ", g: "descendant" }),
    hi: T("term", { t: "वंशज", r: "vaṃśaj", g: "descendant" }),
    bn: T("term", { t: "বংশধর", r: "baṃśadhar", g: "descendant" }),
    ta: T("term", { t: "வழித்தோன்றல்", r: "vaḻittōṉṟal", g: "descendant" }),
    te: T("term", { t: "వంశస్థుడు", r: "vaṃśasthuḍu", g: "descendant" }),
    ar: T("term", { t: "سليل / ذرية", r: "salīl / dhurriyya", g: "descendant" }),
    tr: T("term", { t: "torun / soy", r: "torun / soy", g: "descendant" }),
    iroq: T("class", { t: "remote descending kin" }),
    crow: T("class", { t: "remote descending" }), omaha: T("class", { t: "remote descending" }),
    mur: T("class", { t: "community-specific term" }),
  },

  /* ---- paternal aunt/uncle (chart row 1) ---- */
  PARENT_SIBLING_PAT: {
    zh: T("term", { t: "伯 / 叔 / 姑", r: "bó / shū / gū", g: "F's elder bro / F's younger bro / F's sister", e: "伯/叔 encode seniority relative to father; 姑 marks father's sister.", u: "Highly regional in address forms; standard Mandarin labels shown.", src: "qian" }),
    yue: T("term", { t: "伯父 / 叔叔 / 姑媽", r: "baak3-fu6 / suk1-suk1 / gu1-maa1", g: "F elder bro / F younger bro / F sister", u: "Written forms align with standard Chinese; speech has local forms.", src: "qian" }),
    ja: T("term", { t: "伯父 / 叔父 / 伯母・叔母", r: "oji / oji / oba", g: "elder uncle / younger uncle / aunt", e: "Kanji 伯/叔 encode elder vs younger, though both uncles are read oji.", nb: "Unlike Chinese, Japanese 伯/叔 marks elder-vs-younger relative to the parent, NOT paternal-vs-maternal — the same kanji serve both sides.", src: "kinbank" }),
    ko: T("term", { t: "큰아버지 / 작은아버지 / 고모", r: "keun-abeoji / jageun-abeoji / gomo", g: "F's elder bro / F's younger bro / F's sister", e: "큰/작은 literally 'big/small', marking seniority relative to father.", src: "korean" }),
    vi: T("term", { t: "bác / chú / cô", r: "bác / chú / cô", g: "parent's elder sibling / F's younger bro / F's sister", nb: "bác is side-neutral — it names a parent's ELDER sibling on either side; only chú/cô are specifically paternal-younger.", src: "sidnell" }),
    hi: T("term", { t: "ताऊ / चाचा / बुआ", r: "tāū / cācā / buā", g: "F's elder bro / F's younger bro / F's sister", e: "ताऊ/चाचा split father's brother by seniority.", src: "surya" }),
    bn: T("term", { t: "জ্যাঠা / কাকা / পিসি", r: "jyāṭhā / kākā / pisi", g: "F's elder bro / F's younger bro / F's sister", u: "Regional variants: কাকু, জেঠু, etc.", src: "kinbank" }),
    ta: T("term", { t: "பெரியப்பா / சித்தப்பா / அத்தை", r: "periyappā / cittappā / attai", g: "F's elder bro / F's younger bro / F's sister", e: "பெரிய periya 'big/elder', சின்ன/சித்து 'small/younger'.", src: "dravidian" }),
    te: T("term", { t: "పెద్దనాన్న / చిన్నాన్న / అత్త", r: "peddanānna / cinnānna / atta", g: "F's elder bro / F's younger bro / F's sister", e: "పెద్ద pedda 'elder', చిన్న cinna 'younger'.", src: "dravidian" }),
    ar: T("term", { t: "عم / عمة", r: "ʿamm / ʿamma", g: "father's brother / father's sister", e: "Paternal-side terms are distinct and genealogically salient.", src: "surya" }),
    tr: T("term", { t: "amca / hala", r: "amca / hala", g: "father's brother / father's sister", u: "Also used as respectful address for older non-relatives.", src: "kinbank" }),
    iroq: T("class", { t: "FB may classify AS father; FZ stays distinct (bifurcate-merging).", src: "kinbank" }),
    crow: T("class", { t: "bifurcate-merging plus Crow skewing on the father's-sister line.", src: "kinbank" }),
    omaha: T("class", { t: "bifurcate-merging plus Omaha skewing; FB may merge with father.", src: "kinbank" }),
    mur: T("class", { t: "relational kin term; do not fill from English 'aunt/uncle' without local data.", src: "murrinh" }),
  },
  /* ---- maternal aunt/uncle (chart row 2) ---- */
  PARENT_SIBLING_MAT: {
    zh: T("term", { t: "舅 / 姨", r: "jiù / yí", g: "mother's brother / mother's sister", e: "舅 maternal uncle; 姨 mother's sister.", nb: "姨 also splits by age in careful speech (大姨/小姨) and serves as a generic polite 'auntie'.", src: "qian" }),
    yue: T("term", { t: "舅父 / 姨媽", r: "kau5-fu6 / ji4-maa1", g: "mother's brother / mother's sister", src: "qian" }),
    ja: T("term", { t: "おじ / おば", r: "oji / oba", g: "uncle / aunt", u: "Side (母方の) is added descriptively; the base word is side-neutral.", src: "kinbank" }),
    ko: T("term", { t: "외삼촌 / 이모", r: "oe-samchon / imo", g: "maternal uncle / maternal aunt", e: "외 oe marks the maternal/outside side.", src: "korean" }),
    vi: T("term", { t: "cậu / dì / bác", r: "cậu / dì / bác", g: "M's brother / M's younger sister / parent's elder sibling", nb: "Again bác covers the ELDER maternal sibling; relative age to the parent is decisive.", src: "sidnell" }),
    hi: T("term", { t: "मामा / मौसी", r: "māmā / mausī", g: "mother's brother / mother's sister", src: "surya" }),
    bn: T("term", { t: "মামা / মাসি", r: "māmā / māsi", g: "mother's brother / mother's sister", src: "kinbank" }),
    ta: T("term", { t: "மாமா / சித்தி · பெரியம்மா", r: "māmā / citti · periyammā", g: "mother's brother / mother's younger · elder sister", e: "Maternal uncle (māmā) is structurally central in Dravidian alliance.", u: "Exact maternal-aunt term depends on her age relative to mother.", src: "dravidian" }),
    te: T("term", { t: "మామయ్య / పిన్నీ · పెద్దమ్మ", r: "māmayya / pinnī · peddamma", g: "mother's brother / mother's younger · elder sister", src: "dravidian" }),
    ar: T("term", { t: "خال / خالة", r: "khāl / khāla", g: "mother's brother / mother's sister", src: "surya" }),
    tr: T("term", { t: "dayı / teyze", r: "dayı / teyze", g: "mother's brother / mother's sister", src: "kinbank" }),
    iroq: T("class", { t: "MZ may classify AS mother; MB stays distinct (bifurcate-merging).", src: "kinbank" }),
    crow: T("class", { t: "maternal side often more descriptive; often matrilineal emphasis.", src: "kinbank" }),
    omaha: T("class", { t: "MB line may be generationally skewed (MB ≈ MBS).", src: "kinbank" }),
    mur: T("class", { t: "relational kin term; check community source.", src: "murrinh" }),
  },

  /* ---- first cousins (chart rows 3–6). Sinitic / Arabic / Korean use the composer. ---- */
  "1C_PAT_PARALLEL": {
    zh: T("recipe", { rec: { type: "sinitic", prefix: "堂", pr: "táng" }, g: "paternal-line (agnatic) cousin", e: "堂 points to the agnatic household line.", u: "The cleanest first-cousin category in Mandarin.", src: "qian" }),
    yue: T("recipe", { rec: { type: "sinitic", prefix: "堂", pr: "tong4" }, g: "paternal-line cousin", src: "qian" }),
    ja: T("term", { t: "いとこ（従兄弟・従姉妹）", r: "itoko", g: "cousin", e: "従 marks collateral relation; kanji 兄/弟/姉/妹 disambiguate sex and relative age.", src: "kinbank" }),
    ko: T("recipe", { rec: { type: "korean" }, g: "paternal first cousin", e: "사촌 = 四寸, 'four chon'; 친 marks the close/paternal side.", src: "chon" }),
    vi: T("term", { t: "anh / chị / em họ", r: "anh / chị / em họ", g: "cousin (lit. 'extended-family sibling')", e: "họ marks lineage relation; sibling term encodes age & sex.", src: "sidnell" }),
    hi: T("term", { t: "चचेरा भाई / चचेरी बहन", r: "cacerā bhāī / cacerī bahan", g: "father's-brother's son / daughter", e: "Built on the चाचा line + brother/sister.", src: "surya" }),
    bn: T("term", { t: "জ্যাঠতুতো / খুড়তুতো ভাই-বোন", r: "jyāṭhtuto / khuṛtuto bhāi-bon", g: "paternal-uncle's child", e: "তুতো marks a cousin relation through a specified kin line.", src: "kinbank" }),
    ta: T("term", { t: "அண்ணன் / அக்கா / தம்பி / தங்கை", r: "aṇṇaṉ / akkā / tampi / taṅkai", g: "(parallel cousin = sibling term)", nb: "In Dravidian logic a paternal PARALLEL cousin is classed WITH siblings — there is no separate cousin word; pick the sibling term by age & sex.", src: "dravidian" }),
    te: T("term", { t: "అన్న / అక్క / తమ్ముడు / చెల్లి", r: "anna / akka / tammuḍu / celli", g: "(parallel cousin = sibling term)", nb: "Parallel cousin patterns as a sibling; modern speech may use English 'cousin'.", src: "dravidian" }),
    ar: T("recipe", { rec: { type: "arabic", core: "عم", cr: "ʿamm" }, g: "father's-brother's child", e: "Transparent compound: ibn/bint al-ʿamm 'son/daughter of the paternal uncle'.", u: "Carries special cultural salience in many Arab societies.", src: "surya" }),
    tr: T("term", { t: "kuzen / amca çocuğu", r: "kuzen / amca çocuğu", g: "cousin / paternal-uncle's child", src: "kinbank" }),
    iroq: T("class", { t: "parallel cousin classifies AS a sibling.", src: "kinbank" }),
    crow: T("class", { t: "parallel cousin is sibling-like.", src: "kinbank" }),
    omaha: T("class", { t: "parallel cousin is sibling-like.", src: "kinbank" }),
    mur: T("class", { t: "classified by local subsection/kinship logic.", src: "murrinh" }),
  },
  "1C_PAT_CROSS": {
    zh: T("recipe", { rec: { type: "sinitic", prefix: "表", pr: "biǎo" }, g: "father's-sister's child (cross)", e: "表 marks a cousin outside the agnatic 堂 line; precise form 姑表.", src: "qian" }),
    yue: T("recipe", { rec: { type: "sinitic", prefix: "表", pr: "biu2" }, g: "cross cousin", src: "qian" }),
    ja: T("term", { t: "いとこ", r: "itoko", g: "cousin", src: "kinbank" }),
    ko: T("recipe", { rec: { type: "korean" }, g: "father's-sister's child", e: "고종사촌 gojong-sachon names the FZ-child cross cousin.", src: "chon" }),
    vi: T("term", { t: "anh / chị / em họ", r: "anh / chị / em họ; con cô", g: "father's-sister's child", src: "sidnell" }),
    hi: T("term", { t: "फुफेरा भाई / बहन", r: "phupherā bhāī / bahan", g: "father's-sister's child", src: "surya" }),
    bn: T("term", { t: "পিসতুতো ভাই / বোন", r: "pistuto bhāi / bon", g: "father's-sister's child", src: "kinbank" }),
    ta: T("term", { t: "மச்சான் / மச்சினி", r: "maccāṉ / maccini", g: "male / female cross-cousin (marriageable)", nb: "Filled in from Dravidian alliance terminology — cross cousins are a distinct, marriageable category, not sibling-like. Regional variants: மைத்துனன், அத்தான்.", src: "dravidian" }),
    te: T("term", { t: "బావ / వదిన", r: "bāva / vadina", g: "male / female cross-cousin (marriageable)", nb: "Filled in: bāva/vadina mark the cross-cousin & affinal category; also used for brother-in-law/sister-in-law.", src: "dravidian" }),
    ar: T("recipe", { rec: { type: "arabic", core: "عمة", cr: "ʿamma" }, g: "father's-sister's child", e: "ibn/bint al-ʿamma.", src: "surya" }),
    tr: T("term", { t: "kuzen / hala çocuğu", r: "kuzen / hala çocuğu", g: "father's-sister's child", src: "kinbank" }),
    iroq: T("class", { t: "cross cousin stays distinct, often affinally salient.", src: "kinbank" }),
    crow: T("class", { t: "cross cousin may be generationally skewed.", src: "kinbank" }),
    omaha: T("class", { t: "cross cousin stays distinct.", src: "kinbank" }),
    mur: T("class", { t: "classified by local relational logic.", src: "murrinh" }),
  },
  "1C_MAT_CROSS": {
    zh: T("recipe", { rec: { type: "sinitic", prefix: "表", pr: "biǎo" }, g: "mother's-brother's child (cross)", e: "Precise form 舅表.", src: "qian" }),
    yue: T("recipe", { rec: { type: "sinitic", prefix: "表", pr: "biu2" }, g: "cross cousin", src: "qian" }),
    ja: T("term", { t: "いとこ", r: "itoko", g: "cousin", src: "kinbank" }),
    ko: T("recipe", { rec: { type: "korean" }, g: "mother's-brother's child", e: "외사촌 oe-sachon names the MB-child cousin.", src: "chon" }),
    vi: T("term", { t: "anh / chị / em họ", r: "anh / chị / em họ; con cậu", g: "mother's-brother's child", src: "sidnell" }),
    hi: T("term", { t: "ममेरा भाई / बहन", r: "mamerā bhāī / bahan", g: "mother's-brother's child", src: "surya" }),
    bn: T("term", { t: "মামাতো ভাই / বোন", r: "māmāto bhāi / bon", g: "mother's-brother's child", src: "kinbank" }),
    ta: T("term", { t: "மச்சான் / மச்சினி", r: "maccāṉ / maccini", g: "male / female cross-cousin (marriageable)", nb: "Cross cousin = distinct marriageable category in Dravidian terms.", src: "dravidian" }),
    te: T("term", { t: "బావ / వదిన", r: "bāva / vadina", g: "male / female cross-cousin (marriageable)", src: "dravidian" }),
    ar: T("recipe", { rec: { type: "arabic", core: "خال", cr: "khāl" }, g: "mother's-brother's child", e: "ibn/bint al-khāl.", src: "surya" }),
    tr: T("term", { t: "kuzen / dayı çocuğu", r: "kuzen / dayı çocuğu", g: "mother's-brother's child", src: "kinbank" }),
    iroq: T("class", { t: "cross cousin stays distinct.", src: "kinbank" }),
    crow: T("class", { t: "cross cousin stays distinct.", src: "kinbank" }),
    omaha: T("class", { t: "cross cousin (MB line) may be skewed.", src: "kinbank" }),
    mur: T("class", { t: "classified by local relational logic.", src: "murrinh" }),
  },
  "1C_MAT_PARALLEL": {
    zh: T("recipe", { rec: { type: "sinitic", prefix: "表", pr: "biǎo" }, g: "mother's-sister's child", e: "Precise form 姨表; still 表 (outside the agnatic line).", src: "qian" }),
    yue: T("recipe", { rec: { type: "sinitic", prefix: "表", pr: "biu2" }, g: "mother's-sister's child", src: "qian" }),
    ja: T("term", { t: "いとこ", r: "itoko", g: "cousin", src: "kinbank" }),
    ko: T("recipe", { rec: { type: "korean" }, g: "mother's-sister's child", e: "이종사촌 ijong-sachon names the MZ-child cousin.", src: "chon" }),
    vi: T("term", { t: "anh / chị / em họ", r: "anh / chị / em họ; con dì", g: "mother's-sister's child", src: "sidnell" }),
    hi: T("term", { t: "मौसेरा भाई / बहन", r: "mauserā bhāī / bahan", g: "mother's-sister's child", src: "surya" }),
    bn: T("term", { t: "মাসতুতো ভাই / বোন", r: "māstuto bhāi / bon", g: "mother's-sister's child", src: "kinbank" }),
    ta: T("term", { t: "அண்ணன் / அக்கா / தம்பி / தங்கை", r: "aṇṇaṉ / akkā / tampi / taṅkai", g: "(parallel cousin = sibling term)", nb: "Maternal PARALLEL cousin is sibling-like, like the paternal parallel.", src: "dravidian" }),
    te: T("term", { t: "అన్న / అక్క / తమ్ముడు / చెల్లి", r: "anna / akka / tammuḍu / celli", g: "(parallel cousin = sibling term)", src: "dravidian" }),
    ar: T("recipe", { rec: { type: "arabic", core: "خالة", cr: "khāla" }, g: "mother's-sister's child", e: "ibn/bint al-khāla.", src: "surya" }),
    tr: T("term", { t: "kuzen / teyze çocuğu", r: "kuzen / teyze çocuğu", g: "mother's-sister's child", src: "kinbank" }),
    iroq: T("class", { t: "parallel cousin classifies AS a sibling.", src: "kinbank" }),
    crow: T("class", { t: "parallel cousin is sibling-like.", src: "kinbank" }),
    omaha: T("class", { t: "parallel cousin is sibling-like.", src: "kinbank" }),
    mur: T("class", { t: "classified by local relational logic.", src: "murrinh" }),
  },

  /* ---- once-removed + second cousins + templates (chart rows 7–12) ---- */
  "1C1R_UP": {
    zh: T("term", { t: "堂/表 + 伯/叔/姑/姨…", r: "táng/biǎo + …", g: "parent's first cousin", u: "Descriptive: the 堂/表 prefix combines with a parent's-sibling term.", src: "qian" }),
    yue: T("term", { t: "堂/表 + 伯/叔/姑/姨", r: "tong4/biu2 + …", g: "parent's first cousin", src: "qian" }),
    ja: T("term", { t: "いとこ違い / 親のいとこ", r: "itoko-chigai", g: "parent's cousin", src: "kinbank" }),
    ko: T("term", { t: "오촌", r: "ochon", g: "5-chon kin (parent's first cousin / cousin's parent)", e: "오촌 = 五寸, computed directly from the path length.", src: "chon" }),
    vi: T("term", { t: "bác/chú/cô/cậu/dì họ", r: "bác/chú/cô/cậu/dì họ", g: "parent's cousin (by side & age)", src: "sidnell" }),
    hi: T("term", { t: "पिता/माता के चचेरे… भाई/बहन", r: "pitā/mātā ke cacere… bhāī/bahan", g: "parent's cousin", src: "surya" }),
    bn: T("term", { t: "বাবা/মায়ের …তুতো ভাই/বোন", r: "bābā/māyer …tuto bhāi/bon", g: "parent's cousin", src: "kinbank" }),
    ta: T("term", { t: "descriptive: parent's parallel/cross cousin", r: "", g: "parent's cousin", src: "dravidian" }),
    te: T("term", { t: "descriptive: parent's cousin", r: "", g: "parent's cousin", src: "dravidian" }),
    ar: T("term", { t: "ابن/بنت عم/خال الأب/الأم", r: "ibn/bint ʿamm/khāl al-ʾab/al-ʾumm", g: "parent's cousin (descriptive chain)", src: "surya" }),
    tr: T("term", { t: "anne/babanın kuzeni", r: "anne/babanın kuzeni", g: "parent's cousin", src: "kinbank" }),
    iroq: T("class", { t: "depends on local skewing/extension.", src: "kinbank" }),
    crow: T("class", { t: "skewed by Crow logic.", src: "kinbank" }),
    omaha: T("class", { t: "skewed by Omaha logic.", src: "kinbank" }),
    mur: T("class", { t: "tri-/dyadic relations may be relevant.", src: "murrinh" }),
  },
  "1C1R_DOWN": {
    zh: T("term", { t: "堂/表 + 侄/侄女…", r: "táng/biǎo + zhí(nǚ)…", g: "first cousin's child", src: "qian" }),
    yue: T("term", { t: "堂/表 + 侄/侄女", r: "tong4/biu2 + zat6", g: "cousin's child", src: "qian" }),
    ja: T("term", { t: "いとこ違い / いとこの子", r: "itoko-chigai", g: "cousin's child", src: "kinbank" }),
    ko: T("term", { t: "오촌 조카", r: "ochon joka", g: "5-chon nephew/niece (cousin's child)", src: "chon" }),
    vi: T("term", { t: "cháu họ", r: "cháu họ", g: "cousin's child", src: "sidnell" }),
    hi: T("term", { t: "चचेरे… भाई/बहन का बेटा/बेटी", r: "cacere… bhāī/bahan kā beṭā/beṭī", g: "cousin's child", src: "surya" }),
    bn: T("term", { t: "…তুতো ভাই/বোনের ছেলে/মেয়ে", r: "…tuto bhāi/boner chele/meye", g: "cousin's child", src: "kinbank" }),
    ta: T("term", { t: "descriptive: cousin's son/daughter", r: "", g: "cousin's child", src: "dravidian" }),
    te: T("term", { t: "descriptive: cousin's child", r: "", g: "cousin's child", src: "dravidian" }),
    ar: T("term", { t: "ابن/بنت ابن/بنت العم…", r: "ibn/bint ibn/bint al-ʿamm…", g: "cousin's child (descriptive chain)", src: "surya" }),
    tr: T("term", { t: "kuzenin çocuğu", r: "kuzenin çocuğu", g: "cousin's child", src: "kinbank" }),
    iroq: T("class", { t: "depends on local system.", src: "kinbank" }),
    crow: T("class", { t: "skewed by Crow logic.", src: "kinbank" }),
    omaha: T("class", { t: "skewed by Omaha logic.", src: "kinbank" }),
    mur: T("class", { t: "tri-/dyadic relations may be relevant.", src: "murrinh" }),
  },
  "2C_PAT_AGNATIC": {
    zh: T("term", { t: "再从 + 兄/弟/姐/妹", r: "zàicóng + xiōng/dì/jiě/mèi", g: "second cousin, agnatic line", u: "再从 / 遠房堂- mark the more distant agnatic cousin.", src: "qian" }),
    yue: T("term", { t: "再從 + 兄/弟/姐/妹", r: "zoi3-cung4 + …", g: "second cousin, agnatic", src: "qian" }),
    ja: T("term", { t: "はとこ / またいとこ / 再従兄弟", r: "hatoko / mataitoko / saijūkeitei", g: "second cousin", src: "kinbank" }),
    ko: T("term", { t: "육촌 / 재종", r: "yukchon / jaejong", g: "6-chon kin = second cousin", e: "육촌 = 六寸, computed from path length.", src: "chon" }),
    vi: T("term", { t: "anh/chị/em họ xa", r: "anh/chị/em họ xa", g: "distant cousin", src: "sidnell" }),
    hi: T("term", { t: "दूर का चचेरा भाई/बहन", r: "dūr kā cacerā bhāī/bahan", g: "second (distant) cousin", src: "surya" }),
    bn: T("term", { t: "দূরসম্পর্কের …তুতো ভাই/বোন", r: "dūrsamparker …tuto bhāi/bon", g: "distant cousin", src: "kinbank" }),
    ta: T("term", { t: "extended parallel relation; often descriptive", r: "", g: "second cousin", src: "dravidian" }),
    te: T("term", { t: "descriptive / distant relation", r: "", g: "second cousin", src: "dravidian" }),
    ar: T("term", { t: "ابن ابن عم الأب…", r: "ibn ibn ʿamm al-ʾab…", g: "second cousin (descriptive chain)", src: "surya" }),
    tr: T("term", { t: "ikinci kuzen / uzak kuzen", r: "ikinci kuzen / uzak kuzen", g: "second cousin", src: "kinbank" }),
    iroq: T("class", { t: "may classify by clan/parallel logic, not English degree.", src: "kinbank" }),
    crow: T("class", { t: "skewed / classificatory.", src: "kinbank" }),
    omaha: T("class", { t: "skewed / classificatory.", src: "kinbank" }),
    mur: T("class", { t: "classified by local system; not English degree.", src: "murrinh" }),
  },
  "2C_NONAGNATIC": {
    zh: T("term", { t: "隔代表 / 再表 / 远房表 + 哥/弟/姐/妹", r: "gédài-biǎo / zài-biǎo… + …", g: "second cousin, non-agnatic line", src: "qian" }),
    yue: T("term", { t: "遠房表- / 隔代表-", r: "jyun5-fong4-biu2-…", g: "second cousin, non-agnatic", src: "qian" }),
    ja: T("term", { t: "はとこ / またいとこ", r: "hatoko / mataitoko", g: "second cousin", src: "kinbank" }),
    ko: T("term", { t: "육촌 (+ 외/side modifier)", r: "yukchon", g: "6-chon, with a side modifier", src: "chon" }),
    vi: T("term", { t: "anh/chị/em họ xa", r: "anh/chị/em họ xa", g: "distant cousin (descriptive path)", src: "sidnell" }),
    hi: T("term", { t: "दूर का ममेरा/फुफेरा/मौसेरा भाई/बहन", r: "dūr kā mamerā/phupherā/mauserā…", g: "distant non-agnatic cousin", src: "surya" }),
    bn: T("term", { t: "দূরসম্পর্কের মামাতো/পিসতুতো/মাসতুতো…", r: "dūrsamparker māmāto/pistuto/māstuto…", g: "distant non-agnatic cousin", src: "kinbank" }),
    ta: T("term", { t: "descriptive path; cross/parallel recomputed", r: "", g: "second cousin", src: "dravidian" }),
    te: T("term", { t: "descriptive path / distant relation", r: "", g: "second cousin", src: "dravidian" }),
    ar: T("term", { t: "descriptive chain with عمة/خال/خالة", r: "…", g: "second cousin (descriptive chain)", src: "surya" }),
    tr: T("term", { t: "ikinci kuzen / uzak kuzen", r: "ikinci kuzen / uzak kuzen", g: "second cousin", src: "kinbank" }),
    iroq: T("class", { t: "may classify by cross/parallel/clan logic.", src: "kinbank" }),
    crow: T("class", { t: "skewed / classificatory.", src: "kinbank" }),
    omaha: T("class", { t: "skewed / classificatory.", src: "kinbank" }),
    mur: T("class", { t: "classified by local system; not English degree.", src: "murrinh" }),
  },
  "2C1R_TEMPLATE": {
    zh: T("term", { t: "再从/隔代表 + 侄/侄女 或 伯/叔/姑/姨", r: "(by generation direction)", g: "second cousin once removed", src: "qian" }),
    ko: T("term", { t: "칠촌", r: "chilchon", g: "7-chon kin", e: "칠촌 = 七寸, computed from path length.", src: "chon" }),
    ja: T("term", { t: "はとこ違い / はとこの子 / 親のはとこ", r: "hatoko-chigai", g: "second cousin once removed", src: "kinbank" }),
    ar: T("term", { t: "long descriptive chain", r: "", g: "second cousin once removed", src: "surya" }),
    tr: T("term", { t: "ikinci kuzenin çocuğu", r: "ikinci kuzenin çocuğu", g: "second cousin once removed", src: "kinbank" }),
    iroq: T("class", { t: "template only — check a specific language.", src: "kinbank" }),
    crow: T("class", { t: "template only.", src: "kinbank" }),
    omaha: T("class", { t: "template only.", src: "kinbank" }),
    mur: T("class", { t: "template only.", src: "murrinh" }),
  },
  DISTANT_TEMPLATE: {
    zh: T("term", { t: "族 / 远房 / N从", r: "zú / yuǎnfáng / N-cóng", g: "distant clan kin", src: "qian" }),
    yue: T("term", { t: "族 / 遠房", r: "zuk6 / jyun5-fong4", g: "distant kin", src: "qian" }),
    ja: T("term", { t: "遠い親戚 / 遠縁", r: "tōi shinseki / tōen", g: "distant relative", src: "kinbank" }),
    ko: T("term", { t: "팔촌 / 먼 친척", r: "palchon / meon chincheok", g: "8-chon and beyond / distant kin", src: "chon" }),
    vi: T("term", { t: "họ hàng xa / bà con xa", r: "họ hàng xa", g: "distant relatives", src: "sidnell" }),
    hi: T("term", { t: "दूर का रिश्तेदार", r: "dūr kā rištedār", g: "distant relative", src: "surya" }),
    bn: T("term", { t: "দূরসম্পর্কের আত্মীয়", r: "dūrsamparker ātmīẏa", g: "distant relative", src: "kinbank" }),
    ta: T("term", { t: "தூரத்து உறவினர்", r: "tūrattu uṟaviṉar", g: "distant relative", src: "dravidian" }),
    te: T("term", { t: "దూరపు బంధువు", r: "dūrapu bandhuvu", g: "distant relative", src: "dravidian" }),
    ar: T("term", { t: "قريب بعيد / من الأقارب", r: "qarīb baʿīd / min al-ʾaqārib", g: "a distant relative", src: "surya" }),
    tr: T("term", { t: "uzaktan akraba", r: "uzaktan akraba", g: "distant relative", src: "kinbank" }),
    iroq: T("class", { t: "classificatory remote kin.", src: "kinbank" }),
    crow: T("class", { t: "classificatory remote kin.", src: "kinbank" }),
    omaha: T("class", { t: "classificatory remote kin.", src: "kinbank" }),
    mur: T("class", { t: "template only.", src: "murrinh" }),
  },
};
